events {
    worker_connections 1024;
}

http {
    upstream backends {
        server web1;
        server web2;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backends;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Cabeceras personalizadas para ver en "Inspeccionar Elemento" -> "Red"
            add_header X-Proxy-By "Proxy Inverso - Lautaro" always;
            add_header X-Backend-Server $upstream_addr always;
        }
    }
}
